# Generated by Django 3.0.8 on 2020-10-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('star_system', models.CharField(max_length=30)),
                ('distance', models.FloatField()),
                ('year_of_discovery', models.IntegerField()),
                ('apparent_magnitude', models.FloatField(null=True)),
                ('absolute_magnitude', models.FloatField(null=True)),
            ],
        ),
    ]
