# Generated by Django 3.0.8 on 2020-10-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='year_of_discovery',
            field=models.IntegerField(null=True),
        ),
    ]
