# Generated by Django 3.0.8 on 2020-11-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201104_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='parallax',
            field=models.FloatField(default=1.3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='star',
            name='spectral_class',
            field=models.CharField(choices=[('O', 'O'), ('B', 'B'), ('A', 'A'), ('F', 'F'), ('G', 'G'), ('K', 'K'), ('M', 'M'), ('L', 'L'), ('T', 'T'), ('Y', 'Y')], default='O', max_length=1),
            preserve_default=False,
        ),
    ]
