# Generated by Django 3.0.8 on 2020-11-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201104_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='star',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
