# Generated by Django 3.0.8 on 2020-11-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201105_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='absolute_magnitude',
            new_name='absolut_magnitude',
        ),
    ]
