# Generated by Django 3.0.8 on 2020-11-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201105_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
